### ISSUE TITLE
VSCode automatisch neu laden nach ändern der Umgebungsvariablen

### ISSUE THREAD

**Issue by cakohsh** [hshf1/HSH_AddOn4VSC#14]
Wie von @faBi292 erwähnt, ist ein Neustart nach dem ändern der Umgebungsvariablen notwendig.

**Comment by cakohsh** [comment]
Hier erledigt: https://github.com/hshf1/HSH_AddOn4VSC/commit/ba714afcdeb8aa9e7f1acecc6cdcf805da767c50

**Comment by cakohsh** [comment]
Weiterhin ein Problem, derzeitige Lösung nur Warnmeldung, dass neu gestartet werden soll..

**Comment by cakohsh** [comment]
https://github.com/hshf1/HSH_AddOn4VSC/issues/16#issuecomment-1548786158

wie hier beschrieben VSCode automatisch beenden und Nutzer mit Terminal informieren?

**Comment by cakohsh** [comment]
Ich habe nun das so gemacht, dass die VSCode Meldung in der Bildschirmmitte erscheint und der Nutzer darauf hingewiesen wird, dass VSCode geschlossen wird und manuell neugestartet werden muss. Habe auch die Init dabei angepasst gehabt, würde das heute in die Branch code_kommentare_main hochladen so kannst du das alles zsm mal testen

**Comment by faBi292** [comment]
Alles klar 👍🏽

**Comment by faBi292** [comment]
Es gab ja noch das Problem, dass das await in kombination mit dem exec() Befehl nicht funktioniert hat. Ich habe eine Lösung gefunden. Statt den normalen exec() Befehl zu verweden benutze ich den executeCommand(), die Funktion habe ich erstellt, sie erweitert die exec Funktion um ein Promise. 

export function executeCommand(command: string): Promise<string> {
    return new Promise<string>((resolve, reject) => {
        exec(command, (error: ExecException | null, stdout: string, stderr: string) => {
            if (error) {
                reject(error);
                return;
            }
            resolve(stdout.trim());
        });
    });
}

**Comment by cakohsh** [comment]
Ist das Problem nun vollständig behoben und das Problem kann geschlossen werden?

**Comment by faBi292** [comment]
Jo, aber an für sich wäre es wahrscheinlich schlau es hinzubekommen, dass man VSCode dafür nicht komplett Neu starten muss.

**Comment by cakohsh** [comment]
Alright, dann lassen wir es noch offen
