### ISSUE TITLE
Java Compiler separat installieren, wenn fehlt

### ISSUE THREAD

**Issue by cakohsh** [hshf1/HSH_AddOn4VSC#17]
Java Compiler installieren, wenn fehlt. WINDOWS: über choco was mit LINUX und MAC?

**Comment by faBi292** [comment]
Windows:

choco install openjdk --version=20.0.1 -y     //Zum installieren gleiche Version wie im Computerraum

C:\Program Files\OpenJDK\jdk-20.0.1\bin    //Setzen der Umgebungsvariable

choco uninstall openjdk -y                           //Zum deinstallieren

//Ohne Gewähr /*
Mac:


/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)" //Installiert HomeBrew
brew install --cask adoptopenjdk/openjdk/adoptopenjdk17 //installiert mit HomeBrew die Version 17von JDK

/usr/libexec/java_home -V //Überprüft wo JDK installiert ist
sudo rm -rf /Library/Java/JavaVirtualMachines/jdk-17.jdk //löscht jdk 

Linux:
sudo apt-get install openjdk-17-jdk */

**Comment by cakohsh** [comment]
Die Umgebungsvariable sollte eigentlich mit der choco installation automatisch gesetzt werden. Dennoch sollte der Pfad ggf. mit in die Überprüfung eingehen, sodass wenn der Pfad nicht existiert in den Umgebungsvariablen es diesen hinzufügt wie beim C -Compiler: init.ts Line 272-273 await addNewPath('Pfad-zu-JDK') || ebenfalls für python
