### ISSUE TITLE
Python Compiler separat installieren, wenn fehlt

### ISSUE THREAD

**Issue by cakohsh** [hshf1/HSH_AddOn4VSC#18]
WINDOWS: über choco am einfachsten. MAC und LINUX?

**Comment by faBi292** [comment]
Also der Befehl an sich hatte auch funktioniert, nur es gab noch Komplikationen da der mingw auch zwei Python Versionen installiert und es dadurch zu Verwirrung kam welches Python nun benutzt werden soll.

Habe mir jetzt mal eine cleane Windows 11 Virtual Box aufgesetzt und gerade nochmal den Python Befehl gecheckt und es hat mir diesmal nicht die Version 2.7.9. gezeigt sondern tatsächlich die 3.11.0 :)

Hab diesen Befehl zum installieren verwendet: ```choco install python3 --version=3.11.0 -y```

Und diesen kann man zum deinstallieren verwenden: ```choco uninstall python3 --version=3.11.0 -y```

**Comment by faBi292** [comment]
Update zu Python & Java.

- Befehl zum Sprache wechseln wieder aktiviert und funktionsfähig gemacht.
- Befehl Compiler Check erweitert. Zeigt jetzt in einem Fenster an welche Compiler installiert sind und welche Fehlen. Wenn Compiler fehlen sollten wird der Vorschlag gemacht sie nach zu installieren.
- Ansonsten läuft der Check bei der Initialisierung im Hintergrund ab und führt die Installation automatisch durch.
- Momentan laufen die Installationen noch über das Skript, welches versucht immer alles zu installieren. 
- Windows sollte soweit laufen. Mac steht die Grundstruktur, jedoch muss noch geschaut werden, dass alle Benutzer eingaben bei der Installation automatisiert werden. Linux kommt zum Schluss würd ich sagen. Dann hat man auch direkt die Erfahrung mit den anderen beiden Betriebssystemen.

**Comment by cakohsh** [comment]
Hm war das im letzten Update 1.7.12 drin? Der Befehl zum wechseln der Sprache ist noch nicht aktiviert. Ist noch eine Sperre drin in registercommands.ts line 110-118
